In [1]:
from typing import Tuple

import numpy as np
import pandas as pd

In [2]:
NG= 2;G= 10;N=1000; noiseLevel = 0; ngroups= 1

In [8]:
assert ngroups <= 3, 'Only 3 groups implemented'
    # Construct oscillatory groups
sigma_strLevel = [0.05, 0.1, 0.2, 0.3, 0.4, 0.6]
sigma_str = sigma_strLevel[noiseLevel]

    # two different orders
t1 = np.linspace(0, 2*np.pi, N)
t2 = np.random.permutation(t1)

In [9]:
sigma_strLevel

[0.05, 0.1, 0.2, 0.3, 0.4, 0.6]

In [13]:
t2

array([1.57079633, 4.71238898, 3.14159265, 6.28318531, 0.        ])

In [15]:
data = np.zeros((G, N))
data[:] = np.nan

In [16]:
data

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [21]:
cellName = []

for i in range(N):
    cellName.append('C'+str(i))

    geneName = []

    phaseG = np.zeros((G))
    angularSpeed = np.zeros((G))

In [24]:
cellName

['C0', 'C1', 'C2', 'C3', 'C4']

In [34]:
for i in range(NG):  # strong oscillators
    startingPhase = np.random.uniform(0, 2*np.pi)
    phaseG[i] = startingPhase
    angularSpeed[i] = 2
    data[i, :] = np.sin(2*t1 + startingPhase) + sigma_str*np.random.randn(N)
    geneName.append('G1SO'+str(i))

In [39]:
data.shape



(10, 5)

In [30]:
phaseG

array([3.25700388, 3.26759923, 2.57182413, 3.58264341, 3.67477584,
       0.49045258, 3.72129285, 4.14208743, 1.71733783, 4.14932832])

In [31]:
range(NG)

range(0, 15)

In [40]:
for i in range(NG, 2*NG):  # weak oscillators
    startingPhase = np.random.uniform(0, 2*np.pi)
    phaseG[i] = startingPhase
    angularSpeed[i] = 2
    data[i, :] = np.sin(2*t1 + startingPhase) + 2*sigma_str*np.random.randn(N)
    geneName.append('G1WO'+str(i))

In [47]:
data
np.amax(data)


1.060297775707743

In [42]:
for w in range(i+1, G):  # use i index from above where it stopped
    phaseG[w] = np.nan
    angularSpeed[w] = np.nan
    data[w, :] = np.max([3/2 * sigma_str, 1]) * np.random.randn(N)
    geneName.append('R'+str(w))

In [45]:
assert np.all(~ np.isnan(data)), 'Entries with nans!'
#assert len(geneName) == G
#assert len(cellName) == N
df = pd.DataFrame(data, index=geneName, columns=cellName)

ValueError: Shape of passed values is (10, 5), indices imply (35, 5)